name: DryRun

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        submodules: true
    - name: Help_test
      run: curl -s https://get.nextflow.io | bash && ./nextflow run main.nf --help
    - name: fasta dry run
      run: |
          touch genome.fasta 
          ./nextflow run main.nf --fasta genome.fasta -stub -profile stub
    - name: fasta dry run - tool deactivation 1
      run: |
          touch genome.fasta 
          ./nextflow run main.nf --fasta genome.fasta -stub -profile stub --new_entry --sourmash_off
    - name: fasta dry run - tool deactivation 2
      run: |
          touch genome.fasta 
          ./nextflow run main.nf --fasta genome.fasta -stub -profile stub --output new_result_dir --prokka_off
    - name: fasta dir test
      run: |
          mkdir -p genomes && touch genomes/genome.fasta.gz && touch genomes/genome2.fasta.gz && touch genomes/genome3.fasta.gz 
          ./nextflow run main.nf --fasta genomes/ -stub -profile stub --output result_dir_2
